spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  thymeleaf:
    cache: false

season:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/comment
#    driver-class-name: com.mysql.jdbc.Driver
#    password: 16893714
#    username: root
    master:
      url: jdbc:mysql://localhost:3306/comment?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 16893714
